### ISSUE TITLE
incorrect installation instructions

### ISSUE THREAD

**Issue by bedros** [frdmn/hostkeeper#28]
I'm trying to install on raspberry pi system, so vagrant is not an option, 

in the instructions "installing without vagrant" I got addn-hosts=/vagrant/db.dnsmasq which not possible since vagrant is not installed

**Comment by frdmn** [comment]
@bedros In this case you just need to adjust the `addn-hosts` directive to point to your actual db file which gets generated by hostkeeper. So for example, if you've downloaded/clones the repository into `/opt/hostkeeper/` then change the line to:

```
addn-hosts=/opt/hostkeeper/db.dnsmasq
```

**Comment by frdmn** [comment]
Let me know if you have further questions :)
