### ISSUE TITLE
(API) When edit, check if host already exists

### ISSUE THREAD

**Issue by frdmn** [frdmn/hostkeeper#34]
Since #33, we fixed an issue that you couldn't change the IP of an existing host. However, now since we removed this check, you could potentially end up with 2 identical hosts due to editing a hostname to an already existing one.

**Comment by frdmn** [comment]
@joongimin Could you do me a favor and double check if this solution (https://github.com/frdmn/hostkeeper/commit/e22b3883ef285346c4bd61432fd2097d85564a8c  + da8f683) covers both scenarios?

**Comment by joongimin** [comment]
@frdmn Just checked. It seems your solution covers both scenarios. :+1:

**Comment by frdmn** [comment]
Thanks for testing.

Von meinem iPhone gesendet

**Comment by frdmn** [comment]
Test
